# Generated by Django 5.2.12 on 2026-03-05 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.UUIDField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('gamemode', models.CharField(max_length=50)),
                ('match_type', models.CharField(max_length=50)),
                ('arena', models.CharField(blank=True, max_length=100)),
                ('winner', models.CharField(blank=True, max_length=10)),
                ('score_home', models.IntegerField(blank=True, null=True)),
                ('score_away', models.IntegerField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=50)),
                ('match_length', models.IntegerField(blank=True, null=True)),
                ('current_period', models.IntegerField(blank=True, null=True)),
                ('periods_enabled', models.BooleanField(default=False)),
                ('custom_mercy_rule', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('game_user_id', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('username', 'game_user_id')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=4)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('overtime_wins', models.IntegerField(blank=True, null=True)),
                ('overtime_losses', models.IntegerField(blank=True, null=True)),
                ('shutouts', models.IntegerField(blank=True, null=True)),
                ('shutouts_against', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('primary_assists', models.IntegerField(blank=True, null=True)),
                ('secondary_assists', models.IntegerField(blank=True, null=True)),
                ('contributed_goals', models.IntegerField(blank=True, null=True)),
                ('game_winning_goals', models.IntegerField(blank=True, null=True)),
                ('overtime_goals', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('shots', models.IntegerField(blank=True, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('blocks', models.IntegerField(blank=True, null=True)),
                ('passes', models.IntegerField(blank=True, null=True)),
                ('takeaways', models.IntegerField(blank=True, null=True)),
                ('turnovers', models.IntegerField(blank=True, null=True)),
                ('faceoffs_won', models.IntegerField(blank=True, null=True)),
                ('faceoffs_lost', models.IntegerField(blank=True, null=True)),
                ('post_hits', models.IntegerField(blank=True, null=True)),
                ('games_played', models.IntegerField(blank=True, null=True)),
                ('conceded_goals', models.IntegerField(blank=True, null=True)),
                ('periods_played', models.IntegerField(blank=True, null=True)),
                ('possession_time_sec', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='stats.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='stats.player')),
            ],
            options={
                'unique_together': {('match', 'player', 'team')},
            },
        ),
    ]
