# Generated by Django 5.2.12 on 2026-03-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_user_id', models.CharField(max_length=50, unique=True)),
                ('username_hint', models.CharField(blank=True, help_text='Optional label so you remember who this is', max_length=50)),
            ],
        ),
    ]
