# Generated by Django 5.2.12 on 2026-03-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_whitelistedplayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playermatchstats',
            options={'verbose_name': 'Player Match Stat', 'verbose_name_plural': 'Player Match Stats'},
        ),
        migrations.AlterModelOptions(
            name='whitelistedplayer',
            options={'verbose_name': 'Whitelisted Player', 'verbose_name_plural': 'Whitelisted Players'},
        ),
        migrations.AlterField(
            model_name='player',
            name='game_user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
