# Generated by Django 5.2.12 on 2026-03-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_playermatchstats_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhitelistedPlayer',
        ),
    ]
