# Generated by Django 5.2.12 on 2026-03-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_delete_whitelistedplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingestion_type', models.CharField(choices=[('ALL_PLAYERS', 'All Players'), ('SINGLE_PLAYER', 'Single Player')], default='ALL_PLAYERS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('matches_added', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='stats.player')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ingestion_type', 'ALL_PLAYERS'), ('player__isnull', True)), models.Q(('ingestion_type', 'SINGLE_PLAYER'), ('player__isnull', False)), _connector='OR'), name='player_required_for_single_player')],
            },
        ),
    ]
