# Generated by Django 5.2.12 on 2026-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_ingestionrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
