# Generated by Django 5.2.12 on 2026-03-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_match_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_user_id',
            new_name='slapshot_id',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('username', 'slapshot_id')},
        ),
    ]
